services:
    frontend:
        container_name: synchrona-frontend
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - SYNCH_BACKEND_URL=${BACKEND_URL}
        ports:
            - 4200:4200
